#!/bin/bash

for i in "$@"; do

seconds=0
minutes=0
hours=0

    command=`exiftool  "$i" | grep -m1 Duration`
    
    if [[ $command == *"s"* ]]; then
    seconds=`exiftool  "$i" | grep -m1 Duration | cut -c 35-36 | sed 's/\.//g'`

    else
    
    #Getting the durations from the files with exiftool
    time=`exiftool  "$i" | grep -m1 Duration | grep -o [0-9]:[0-5][0-9]:[0-5][0-9]`
    
    #Extracting the hours, minutes and seconds
    hours=`cut -c 1 <<< $time`
    minutes=`cut -c 3-4 <<< $time`
    seconds=`cut -c 6-7 <<< $time`
    
    fi
    
    #Summing up the minutes and seconds
    minsum=`expr $minsum + $minutes`
    secsum=`expr $secsum + $seconds`
    hsum=`expr $hsum + $hours`

done

    #Conversion to the sexagesimal system of the time
    secrest=`expr $secsum % 60`
    secdiv=`expr $secsum / 60`
    minsum=`expr $minsum + $secdiv`
    minrest=`expr $minsum % 60`
    mindiv=`expr $minsum / 60`
    hsum=`expr $hsum + $mindiv`
    
    #Leading zero in case the minute and/or second is smaller than 10
    seczero=""
    minzero=""
    
    if [ $minrest -lt 10 ]; then
    minzero=0
    fi
    
    if [ $secrest -lt 10 ]; then
    seczero=0
    fi
  
  #Output of the result in the normal time format
echo Total duration: $hsum:$minzero$minrest:$seczero$secrest
